data:
  num_classes: 10
  dataset_name: "Animal-10N"
  data_path: '/data1/yuqi/data/Animal-10N' 

classifier:
  classifier_save_path: "/data1/yuqi/clip/Animal-10N/submit/zero_shot_classifier.pth"   # The classifier is initialized with label text features.
  synsets_path: "/data1/yuqi/data/Animal-10N/category_names.txt"      # category name path
  template_name: "simple_template"             #  "openai_imagenet_template"，"simple_template" 


clip:
  model_type: ["ViT-L-14", 'datacomp_xl_s13b_b90k']
  pretrained_model_path: "/data1/yuqi/data/pretrained_model/clip_ViT-L-14.pth"


stage2:
  K: 10                                                             # Number of augmentations per image
  th: 0.7                                                           # Clean sample selection threshold
  consistency_score_save_path: "./det_clean_noisy.json"             # Confidence score file path
  finetuned_model_path: "./checkpoint/checkpoint_finetune_total/best_model.pth"   # Used when zero-shot performance is poor.
  finetuned_model_path: None
  
stage3:
  batch_size: 32
  base_lr: 0.0005
  warm_up_epochs: 3
  num_epochs: 20
  num_workers: 5
  resume: 0
  checkpoint_dir: "./checkpoint/checkpoint_semi"    # Model save path 
  T: 2                   # Temperature coefficient
  threshold: 0.95        # Threshold for selecting high-confidence pseudo labels
  lambda_u: 0.5          # Loss weight for noisy samples


finetune:
  batch_size: 32
  base_lr: 0.0005
  num_epochs: 5
  num_workers: 5
  resume: 0
  # checkpoint_dir: "./checkpoint/checkpoint_finetune_clean"    # Model save path 
  # train_mode: "finetune_clean"    # choices=["finetune_clean", "finetune_total"]
  checkpoint_dir: "./checkpoint/checkpoint_finetune_total"    # Model save path 
  train_mode: "finetune_total"    # choices=["finetune_clean", "finetune_total"]



model_ensemble:
  trained_model_path: "./checkpoint/checkpoint_semi"        
  alpha_list: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9] 

 

test:
  test_model_path: ""             # Zero-shot
  # test_model_path:  "./checkpoint/checkpoint_semi/best_model.pth"   # Test the trained model