# synthetic noise
generate_noisy_data: 
  noise_mode: 'asym'
  noise_ratio: 0.4

data:
  num_classes: 10
  dataset_name: "cifar10"
  data_path: '/data1/yuqi/data/cifar10' 

classifier:
  classifier_save_path: "/data1/yuqi/clip/CIFAR/submit/pretrained_model/zero_shot_classifier_cifar10.pth"   # The classifier is initialized with label text features.
  synsets_path: "/data1/yuqi/data/cifar10/category_names_eng.txt"      # category name path
  template_name: "simple_template"             #  "openai_imagenet_template"，"simple_template" 


clip:
  model_type: ["ViT-L-14", 'datacomp_xl_s13b_b90k']
  pretrained_model_path: "/data1/yuqi/data/pretrained_model/clip_ViT-L-14.pth"


stage2:
  K: 10                                                             # Number of augmentations per image
  th: 0.7                                                           # Clean sample selection threshold
  consistency_score_save_path: "/data1/yuqi/data/cifar10/det_clean_noisy.json"             # Confidence score file path
  

stage3:
  batch_size: 32
  base_lr: 0.0005
  warm_up_epochs: 3
  num_epochs: 20
  num_workers: 5
  resume: 0
  checkpoint_dir: "./checkpoint_cifar10/asym_0.4/checkpoint_semi"    # Model save path 
  noise_type: "asym"                        # choices=["sym", "asym"]
  noise_ratio: 0.4
  T: 1                   # Temperature coefficient
  threshold: 0.95        # Threshold for selecting high-confidence pseudo labels
  lambda_u: 0.5          # Loss weight for noisy samples


finetune:
  batch_size: 32
  base_lr: 0.0005
  num_epochs: 20
  num_workers: 5
  resume: 0
  # checkpoint_dir: "./checkpoint_cifar10/asym_0.4/finetune_total"    # Model save path 
  checkpoint_dir: "./checkpoint_cifar10/finetune_total"    # Model save path 
  noise_type: "asym"     # choices=["sym", "asym"]
  noise_ratio: 0.4
  train_mode: "finetune_total"    # choices=["finetune_clean", "finetune_total"]



model_ensemble:
  trained_model_path: "./checkpoint_cifar10/asym_0.4/checkpoint_semi"       
  alpha_list: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9] 

 

test:
  # test_model_path: ""             # Zero-shot
  test_model_path:  "./checkpoint_cifar10/asym_0.4/checkpoint_semi/best_model.pth"   # Test the trained model